# Generated by Django 5.2.4 on 2025-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0002_pedido_itempedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
