# Generated by Django 5.2.4 on 2025-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0003_cliente_is_active_cliente_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="is_staff",
            new_name="is_admin",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="cliente",
            name="pontos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ultimo_endereco",
            field=models.TextField(blank=True, null=True),
        ),
    ]
