# Generated by Django 5.2.4 on 2025-07-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0004_rename_is_staff_cliente_is_admin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="data",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="preco_unitario",
        ),
        migrations.AddField(
            model_name="itempedido",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="pedido",
            name="bairro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cardapio.bairro",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="endereco_entrega",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_entrega",
            field=models.CharField(
                choices=[
                    ("entrega", "Entrega"),
                    ("retirada", "Retirada"),
                    ("local", "Consumir no Local"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
