# Generated by Django 5.2.4 on 2025-08-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0005_rename_data_pedido_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(default="dinheiro_pix", max_length=20),
        ),
    ]
