# Generated by Django 5.2.4 on 2025-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0006_pedido_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="troco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_preparo", "Em preparo"),
                    ("pronto", "Pronto para retirada"),
                    ("a_caminho", "A caminho"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
