# Generated by Django 5.2.4 on 2025-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0007_pedido_endereco_pedido_troco_alter_pedido_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loja_aberta", models.BooleanField(default=True)),
            ],
        ),
    ]
