# Generated by Django 5.2.4 on 2025-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0008_configuracaoloja"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="cor",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Cor em formato hexadecimal, ex: #FF5733",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="icone_bootstrap",
            field=models.CharField(
                blank=True,
                help_text="Nome do ícone Bootstrap, ex: bi bi-pizza",
                max_length=50,
                null=True,
            ),
        ),
    ]
