# Generated by Django 5.2.4 on 2025-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0009_categoria_cor_categoria_icone_bootstrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
