# Generated by Django 5.2.4 on 2025-08-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0010_produto_estoque"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("g", "Gramas"),
                            ("kg", "Quilogramas"),
                            ("un", "Unidades"),
                            ("ml", "Mililitros"),
                            ("l", "Litros"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "estoque_atual",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "custo_unidade",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Custo por grama, unidade, ml, etc.",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.insumo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receita",
                        to="cardapio.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="insumos",
            field=models.ManyToManyField(
                through="cardapio.ItemReceita", to="cardapio.insumo"
            ),
        ),
    ]
