# Generated by Django 5.2.4 on 2025-08-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0011_insumo_itemreceita_produto_insumos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ultimo_bairro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cardapio.bairro",
            ),
        ),
    ]
