# Generated by Django 5.2.4 on 2025-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0012_cliente_ultimo_bairro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="troco",
        ),
        migrations.AddField(
            model_name="pedido",
            name="troco_para",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(default="dinheiro", max_length=20),
        ),
    ]
