# Generated by Django 5.2.4 on 2025-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0014_webpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="ordem",
            field=models.PositiveIntegerField(
                default=0, help_text="Use 0, 1, 2... para definir a ordem de exibição"
            ),
        ),
    ]
